
export const GIT_GET_ISWORKINGTREE="GIT_GET_ISWORKINGTREE";
export const GIT_SET_ISWORKINGTREE="GIT_SET_ISWORKINGTREE";

export const GIT_GET_BRANCHES="GIT_GET_BRANCHES";
export const GIT_SET_BRANCHES="GIT_SET_BRANCHES";

export const GIT_GET_REMOTEBRANCHES="GIT_GET_REMOTEBRANCHES";
export const GIT_SET_REMOTEBRANCHES="GIT_SET_REMOTEBRANCHES";

export const GIT_GET_WORKINGBRANCH="GIT_GET_WORKINGBRANCH";
export const GIT_SET_WORKINGBRANCH="GIT_SET_WORKINGBRANCH";

export const GIT_GET_STATUS="GIT_GET_STATUS";
export const GIT_SET_STATUS="GIT_SET_STATUS";