
export const GIT_GET_ISWORKINGTREE="GIT_GET_ISWORKINGTREE";
export const GIT_SET_ISWORKINGTREE="GIT_SET_ISWORKINGTREE";

export const GIT_GET_BRANCHES="GIT_GET_BRANCHES";
export const GIT_SET_BRANCHES="GIT_SET_BRANCHES";