export const WEBSOCKET_CONNECT = "WEBSOCKET_CONNECT";

export const SERVICE_SET_STATEOPEN = "SERVICE_SET_STATEOPEN";
export const SERVICE_SET_STATECLOSED = "SERVICE_SET_STATECLOSED";
export const SERVICE_SET_SERVICE_STATE = "SERVICE_SET_SERVICE_STATE";
export const SERVICES_SET_AVAILABLE = "SERVICES_SET_AVAILABLE";
export const SERVICES_SET_AVAILABLEERROR = "SERVICES_SET_AVAILABLEERROR";

export const SERVICE_START = "SERVICE_START";

export const SERVICE_PING = "SERVICE_PING";
export const SERVICE_PING_RECEIVED = "SERVICE_PING_RECEIVED";

export const SERVICE_KILL = "SERVICE_KILL";
export const SERVICE_KILL_ALL = "SERVICE_KILL_ALL";
export const SERVICE_LOG_HISTORY = "SERVICE_LOG_HISTORY";
export const SERVICE_ADD_CONFIG = "SERVICE_ADD_CONFIG";
export const SERVICE_DELETE_CONFIG = "SERVICE_DELETE_CONFIG";
export const SERVICE_EDIT_CONFIG = "SERVICE_EDIT_CONFIG";
export const SERVICE_CLEAR_LOGS = "SERVICE_CLEAR_LOGS";
