

export const CONNECT_WEBSOCKET = "CONNECT_WEBSOCKET";

export const SET_STATEOPEN = "SET_STATEOPEN";
export const SET_STATECLOSED = "SET_STATECLOSED";
export const SET_SERVICE_STATE = "SET_SERVICE_STATE";
export const SET_AVAILABLESERVICES = "SET_AVAILABLESERVICES";
export const SET_AVAILABLESERVICESERROR = "SET_AVAILABLESERVICESERROR";

export const START_SERVICE = "START_SERVICE";

export const PING_SERVICE = "PING_SERVICE";

export const KILL_SERVICE = "KILL_SERVICE";
export const ADD_SERVICE_CONFIG = "ADD_SERVICE_CONFIG";
export const DELETE_SERVICE_CONFIG = "DELETE_SERVICE_CONFIG";
export const EDIT_SERVICE_CONFIG = "EDIT_SERVICE_CONFIG";
export const SET_MEMORY_USAGE = "SET_MEMORY_USAGE";
export const CLEAR_MEMORY_USAGE = "CLEAR_MEMORY_USAGE";
export const UPDATE_TERMINAL = "UPDATE_TERMINAL";

