

export const CONNECT_WEBSOCKET = "CONNECT_WEBSOCKET";

export const SET_STATEOPEN = "SET_STATEOPEN";
export const SET_STATECLOSED = "SET_STATECLOSED";
export const SET_SERVICE_STATE = "SET_SERVICE_STATE";
export const SET_AVAILABLESERVICES = "SET_AVAILABLESERVICES";
export const SET_AVAILABLESERVICESERROR = "SET_AVAILABLESERVICESERROR";

export const START_SERVICE = "START_SERVICE";

export const PING_SERVICE = "PING_SERVICE";
export const PING_RESET = "PING_RESET";
export const PING_SERVICERECEIVED = "PING_SERVICERECEIVED";

export const KILL_SERVICE = "KILL_SERVICE";
export const LOG_HISTORY_SERVICE = "LOG_HISTORY_SERVICE";
export const ADD_SERVICE_CONFIG = "ADD_SERVICE_CONFIG";
export const DELETE_SERVICE_CONFIG = "DELETE_SERVICE_CONFIG";
export const EDIT_SERVICE_CONFIG = "EDIT_SERVICE_CONFIG";
