export const WEBSOCKET_CONNECT = "WEBSOCKET.CONNECT";
export const WEBSOCKET_CONNECTED = "WEBSOCKET.CONNECTED";
export const WEBSOCKET_DISCONNECTED = "WEBSOCKET.DISCONNECTED";
export const WEBSOCKET_ERROR = "WEBSOCKET.ERROR";
export const WEBSOCKET_RECEIVED = "WEBSOCKET.RECEIVED";
export const WEBSOCKET_SEND = "WEBSOCKET.SEND";
export const WEBSOCKET_DISMISS = "WEBSOCKET.DISMISS";
export const WEBSOCKET_EVENTS = "WEBSOCKET.EVENTS";
